type Transaction = {
  
  /** Date the transaction occures */
  date: GregorianCalendar,

  /** Text identifier of the transaction(sets by the bank)*/
  textIdentifier: string,

  /** Transaction value */
  value: number,

  /** Extra informations about the transaction */
  description: string,

  /** Number of the DOC */
  docID: string

  /** The types of the transaction */
  transactionTypes: string[]
}

type GregorianCalendar = {
  year?: number,
  month?: number,
  dayOfMonth?: number
}

enum TransactionType {
  SALDO_CORRENTE = "SALDO_CORRENTE", 
  VALOR_APLICACAO = "VALOR_APLICACAO",
  RECEITA_OPERACIONAL = "RECEITA_OPERACIONAL", 
  TAXA_CONDOMINIO = "TAXAS_DE_CONDOMINIO",
  TAXA_EXTRA = "TAXAS_EXTRAS",
  TAXA_SALAO_FESTA = "TAXAS_SALAO_DE_FESTAS",
  MULTAS_JUROS = "MULTAS_E_JUROS",
  TAXA_AGUA = "TAXA_DE_AGUA",
  RECUPERACAO_ATIVOS  = "RECUPERACAO_DE_ATIVOS",
  MULTA_JURO_CORRECAO_COBRANCA = "MULTA_JUROS_E_CORRECAO_DE_COBRANCA",
  OUTRAS_RECEITAS = "OUTRAS_RECEITAS",
  DESPESAS_PESSOAL = "DESPESAS_COM_PESSOAL",
  TERCEIRIZACAO_FUNCIONARIOS = "TERCEIRIZACAO_DE_FUNCIONARIOS",
  VIGILANCIA = "VIGILANCIA",
  SALARIO_FUNCIONARIOS_ORGANICOS = "SALARIO_DOS_FUNCIONARIOS_ORGANICOS",
  ADIANTAMENTO_SALARIAL_FUNCIONARIOS_ORGANICOS = "ADIANTAMENTO_SALARIAL_DOS_FUNCIONARIOS_ORGANICOS",
  FERIAS = "FERIAS",
  INSS = "INSS_FUNCIONARIOS_E_VIGILANCIA",
  FGTS = "FGTS",
  PIS = "PIS",
  ISS = "ISS",
  BENEFICIO_SOCIAL = "BENEFICIO_SOCIAL_DOS_FUNCIONARIOS_ORGANICOS",
  OUTRAS_DESPESAS_PESSOAL = "OUTRAS_DESPESAS_COM_PESSOAL",
  DESPESAS_ADMINISTRATIVAS = "DESPESAS_ADMINISTRATIVAS",
  ENERGISA = "ENERGISA",
  CAGEPA = "CAGEPA",
  COMPRA = "COMPRA",
  ADMINISTRACAO_CONDOMINIO = "ADMINISTRACAO_DO_CONDOMINIO",
  MANUTENCAO = "MANUTENCAO_REALIZADA",
  ABASTECIMENTO = "ABASTECIMENTOS",
  SERVICOS_TERCEIROS = "SERVICOS_REALIZADOS_POR_TERCEIROS",
  IRPF = "IMPOSTO_DE_RENDA_RECOLHIDO_NA_FONTE",
  TARIFAS_BANCARIAS = "TARIFAS_E_TAXAS_BANCARIAS",
  OUTRAS_DESPESAS_ADMINISTRATIVAS = "OUTRAS_DESPESAS_ADMINISTRATIVAS",
  APLICACAO = "APLICACAO",
  OUTROS = "OUTROS"
}

export {
  Transaction,
  GregorianCalendar,
  TransactionType
}
